version: "3.3"

services:
  nodejs:
    container_name: nodejsAPI
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
    restart: unless-stopped
    user: "node"
    env_file: ./api/.env
    environment:
      APP_NAME: chatbotAPI
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - '3000:3000'
  bot:
    container_name: discordBOT
    build:
      context: .
      dockerfile: ./.docker/discord.dockerfile
    restart: unless-stopped
    user: "discordbot"
    env_file: ./bot/.env
    environment:
      APP_NAME: chatbotAPI
    stdin_open: true
    tty: true
  python:
    container_name: pythonAI
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
    restart: unless-stopped
    user: "python"
    environment:
      APP_NAME: chatbotAPI
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - '12345:12345'
