DROP DATABASE IF EXISTS chatbotAPI;
CREATE DATABASE chatbotAPI;
USE chatbotAPI;

CREATE TABLE apiTokens(
  ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  token VARCHAR(255) NOT NULL,
  created TIMESTAMP(1) NOT NULL DEFAULT CURRENT_TIMESTAMP(1)
);

CREATE TABLE requests(
  ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  tokenFK INT UNSIGNED NOT NULL,
  msg TEXT NOT NULL,
  received TIMESTAMP(1) NOT NULL DEFAULT CURRENT_TIMESTAMP(1),
  response TEXT,
  FOREIGN KEY (tokenFK) REFERENCES apiTokens(ID)
);

INSERT INTO apiTokens (token) VALUES ('oz1DRx0rDFlNHKsg3u');