DROP DATABASE IF EXISTS chatbotAPI;
CREATE DATABASE chatbotAPI;
USE chatbotAPI;

CREATE TABLE apiTokens(
  token VARCHAR(255) PRIMARY KEY,
  created TIMESTAMP(1) NOT NULL DEFAULT CURRENT_TIMESTAMP(1)
);

CREATE TABLE requests(
  tokenFK VARCHAR(255) NOT NULL,
  msg TEXT NOT NULL,
  received TIMESTAMP(1) NOT NULL DEFAULT CURRENT_TIMESTAMP(1),
  FOREIGN KEY (tokenFK) REFERENCES apiTokens(token)
);

INSERT INTO apiTokens (token) VALUES ('oz1DRx0rDFlNHKsg3u');