DROP DATABASE IF EXISTS chatbotAI;
CREATE DATABASE chatbotAI;
USE chatbotAI;

CREATE TABLE apiTokens(
  ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  token VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP(1) NOT NULL DEFAULT CURRENT_TIMESTAMP(1)
);
